basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: API文档
  title: online_exercise_system
  version: "1.0"
paths:
  /email/code:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","token":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem/list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /register:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: email
        in: formData
        name: email
        type: string
      - description: code
        in: formData
        name: code
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
swagger: "2.0"
