basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: API文档
  title: online_exercise_system
  version: "1.0"
paths:
  /email/code:
    post:
      parameters:
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"","token":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem/detail:
    get:
      parameters:
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem/list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /rank_list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":""}'
          schema:
            type: string
      summary: 用户排行
      tags:
      - 公共方法
  /register:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: email
        in: formData
        name: email
        type: string
      - description: code
        in: formData
        name: code
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /submit_list:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 用户提交列表
      tags:
      - 公共方法
  /u/admin/category_add:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parent_identity
        in: formData
        name: parent_identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 添加分类
      tags:
      - 管理员私有方法
  /u/admin/category_del:
    delete:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: category_identity
        in: query
        name: category_identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 删除分类
      tags:
      - 管理员私有方法
  /u/admin/category_list:
    get:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 更新分类
      tags:
      - 管理员私有方法
  /u/admin/problem/add:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        type: integer
      - description: category_ids
        in: formData
        name: category_ids
        type: array
      - description: test_cases
        in: formData
        name: test_cases
        required: true
        type: array
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 创建问题
      tags:
      - 管理员私有方法
  /u/admin/submit:
    post:
      parameters:
      - description: authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: problem_identity
        in: query
        name: problem_identity
        required: true
        type: string
      - description: code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 提交代码
      tags:
      - 用户方法
  /u/detail:
    get:
      responses:
        "200":
          description: '{"code":"200","msg":"",data:""}'
          schema:
            type: string
      summary: 用户信息详情
      tags:
      - 用户组
swagger: "2.0"
